name: edgex-device-mqtt
base: core20
license: Apache-2.0
adopt-info: device-mqtt
summary: Connect data MQTT to EdgeX using device-mqtt reference Device Service
title: EdgeX MQTT Device Service
description: |
  The official reference EdgeX device-mqtt Device Service built using the 
  device-sdk-go to interact with MQTT brokers. 
  Initially the daemon in the snap is disabled - a device profile must be
  provisioned externally with core-metadata or provided to device-mqtt inside
  "$SNAP_DATA/config/device-mqtt/res" before starting.

# TODO: add armhf when the project supports this
architectures:
  - build-on: amd64
  - build-on: arm64

grade: stable
confinement: strict

# edinburgh, geneva,hanoi = 1, ireland = 2
epoch: 2

slots:
  edgex-secretstore-token:
    interface: content
    content: edgex-secretstore-token
    source:
      write: [$SNAP_DATA/device-mqtt]

apps:
  device-mqtt:
    adapter: full
    command: bin/device-mqtt -confdir $SNAP_DATA/config/device-mqtt -profile res --registry $CONSUL_ADDR
    command-chain:
      - bin/startup-env-var.sh
    environment:
      CONSUL_ADDR: "consul://localhost:8500"
      DEVICE_PROFILESDIR: $SNAP_DATA/config/device-mqtt/res/profiles
      DEVICE_DEVICESDIR: $SNAP_DATA/config/device-mqtt/res/devices
      SECRETSTORE_TOKENFILE: $SNAP_DATA/device-mqtt/secrets-token.json
      WRITABLE_LOGLEVEL: 'INFO'
    daemon: simple
    install-mode: disable
    plugs: [network, network-bind]

plugs:
  device-config:
    interface: content
    content: device-config
    target: $SNAP_DATA/config/device-mqtt/res

parts:

  hooks:
    source: snap/local/hooks
    plugin: make
    build-snaps:
      - go/1.16/stable
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      make build
      install -DT ./cmd/configure/configure "$SNAPCRAFT_PART_INSTALL/snap/hooks/configure"
      install -DT ./cmd/install/install "$SNAPCRAFT_PART_INSTALL/snap/hooks/install"

  device-mqtt:
    source: .
    plugin: make
    build-packages: [git, libzmq3-dev, zip, pkg-config]
    stage-packages: [libzmq5]
    build-snaps:
      - go/1.16/stable
    override-build: |
      cd $SNAPCRAFT_PART_SRC

      GIT_VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
      if [ -z "$GIT_VERSION" ]; then
        GIT_VERSION="0.0.0"
      fi
      snapcraftctl set-version ${GIT_VERSION}
      # this is needed for make build
      echo $GIT_VERSION > ./VERSION

      go mod tidy
      make build

      install -DT "./cmd/device-mqtt" "$SNAPCRAFT_PART_INSTALL/bin/device-mqtt"
      install -DT "./cmd/res/configuration.toml" "$SNAPCRAFT_PART_INSTALL/config/device-mqtt/res/configuration.toml"

      install -DT "./cmd/res/devices/mqtt.test.device.toml" \
        "$SNAPCRAFT_PART_INSTALL/config/device-mqtt/res/devices/mqtt.test.device.toml"
      install -DT "./cmd/res/devices/mqtt.test.device.toml" \
        "$SNAPCRAFT_PART_INSTALL/config/device-mqtt/res/devices/mqtt.test.device.toml"
      install -DT "./cmd/res/profiles/mqtt.test.device.profile.yml" \
        "$SNAPCRAFT_PART_INSTALL/config/device-mqtt/res/profiles/mqtt.test.device.profile.yml"

      install -DT "./Attribution.txt" \
         "$SNAPCRAFT_PART_INSTALL/usr/share/doc/device-mqtt/Attribution.txt"
      install -DT "./LICENSE" \
         "$SNAPCRAFT_PART_INSTALL/usr/share/doc/device-mqtt/LICENSE"

  config-common:
    plugin: dump
    source: snap/local/runtime-helpers
