name: edgex-device-mqtt
base: core18
version: "replace-me"
license: Apache-2.0
version-script: |
  echo $(cat VERSION)-$(date +%Y%m%d)+$(git rev-parse --short HEAD)
summary: Connect data MQTT to EdgeX using device-mqtt reference Device Service
title: EdgeX MQTT Device Service
description: |
  The official reference EdgeX device-mqtt Device Service built using the 
  device-sdk-go to interact with MQTT brokers. 
  Initially the daemon in the snap is disabled - a device profile must be
  provisioned externally with core-metadata or provided to device-mqtt inside
  "$SNAP_DATA/config/device-mqtt/res" before starting.

# TODO: add armhf when the project supports this
architectures:
  - build-on: amd64
  - build-on: arm64

grade: stable
confinement: strict

# edinburgh release is epoch 1
epoch: 1

apps:
  device-mqtt:
    adapter: none
    command: bin/device-mqtt -confdir $SNAP_DATA/config/device-mqtt -profile res --registry $CONSUL_ADDR
    environment:
      CONSUL_ADDR: "consul://localhost:8500"
    daemon: simple
    plugs: [network, network-bind]

parts:
  go:
    plugin: nil
    source: snap/local
    build-packages: [curl]
    override-build: |
      # use dpkg architecture to figure out our target arch
      # note - we specifically don't use arch
      case "$(dpkg --print-architecture)" in
        amd64)
          FILE_NAME=go1.13.5.linux-amd64.tar.gz
          FILE_HASH=512103d7ad296467814a6e3f635631bd35574cab3369a97a323c9a585ccaa569
          ;;
        arm64)
          FILE_NAME=go1.13.5.linux-arm64.tar.gz
          FILE_HASH=227b718923e20c846460bbecddde9cb86bad73acc5fb6f8e1a96b81b5c84668b
          ;;
        armhf)
          FILE_NAME=go1.13.5.linux-armv6l.tar.gz
          FILE_HASH=26259f61d52ee2297b1e8feef3a0fc82144b666a2b95512402c31cc49713c133
          ;;
        i386)
          FILE_NAME=go1.13.5.linux-386.tar.gz
          FILE_HASH=3b830fa25f79ab08b476f02c84ea4125f41296b074017b492ac1ff748cf1c7c9
          ;;
      esac
      # download the archive, failing on ssl cert problems
      curl https://dl.google.com/go/$FILE_NAME -O
      echo "$FILE_HASH $FILE_NAME" > sha256
      sha256sum -c sha256 | grep OK
      tar -C $SNAPCRAFT_STAGE -xf go*.tar.gz --strip-components=1
    prime:
      - "-*"

  device-mqtt:
    source: .
    plugin: make
    build-packages: [git]
    after: [go]
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      make build

      install -DT "./cmd/device-mqtt" "$SNAPCRAFT_PART_INSTALL/bin/device-mqtt"

      # FIXME: settings can't be overridden from the cmd-line!
      # Override 'LogFile' and 'LoggingRemoteURL'
      install -d "$SNAPCRAFT_PART_INSTALL/config/device-mqtt/res/"

      cat "./cmd/res/example/configuration.toml" | \
        sed -e s:\"./device-mqtt.log\":\'\$SNAP_COMMON/device-mqtt.log\': \
          -e s:'ProfilesDir = \"./res/example\"':'ProfilesDir = \"\$SNAP_DATA/config/device-mqtt/res\"': > \
        "$SNAPCRAFT_PART_INSTALL/config/device-mqtt/res/configuration.toml"

      install -DT "./cmd/res/example/mqtt.test.device.profile.yml" \
        "$SNAPCRAFT_PART_INSTALL/config/device-mqtt/res/mqtt.test.device.profile.yml"

      install -DT "./Attribution.txt" \
         "$SNAPCRAFT_PART_INSTALL/usr/share/doc/device-mqtt/Attribution.txt"
      install -DT "./LICENSE" \
         "$SNAPCRAFT_PART_INSTALL/usr/share/doc/device-mqtt/LICENSE"
