name: edgex-device-mqtt
base: core20
license: Apache-2.0
adopt-info: metadata

architectures:
  - build-on: amd64
  - build-on: arm64

grade: stable
confinement: strict

# 1: edinburgh, geneva, hanoi
# 2: ireland, jakarta
epoch: 2

slots:
  edgex-secretstore-token:
    interface: content
    content: edgex-secretstore-token
    source:
      write: [$SNAP_DATA/device-mqtt]

apps:
  device-mqtt:
    adapter: full
    command: bin/device-mqtt -confdir $SNAP_DATA/config/device-mqtt -profile res --registry $CONSUL_ADDR
    command-chain:
      - bin/startup-env-var.sh
    environment:
      CONSUL_ADDR: "consul://localhost:8500"
      DEVICE_PROFILESDIR: $SNAP_DATA/config/device-mqtt/res/profiles
      DEVICE_DEVICESDIR: $SNAP_DATA/config/device-mqtt/res/devices
      SECRETSTORE_TOKENFILE: $SNAP_DATA/device-mqtt/secrets-token.json
      WRITABLE_LOGLEVEL: 'INFO'
    daemon: simple
    install-mode: disable
    plugs: [network, network-bind]

plugs:
  device-config:
    interface: content
    target: $SNAP_DATA/config/device-mqtt

parts:

  hooks:
    source: snap/local/hooks
    plugin: make
    build-snaps:
      - go/1.17/stable
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      make build
      install -DT ./cmd/configure/configure "$SNAPCRAFT_PART_INSTALL/snap/hooks/configure"
      install -DT ./cmd/install/install "$SNAPCRAFT_PART_INSTALL/snap/hooks/install"

  device-mqtt:
    after: [metadata]
    source: .
    plugin: make
    build-packages: [git, libzmq3-dev, zip, pkg-config]
    stage-packages: [libzmq5]
    build-snaps:
      - go/1.17/stable
    override-build: |
      cd $SNAPCRAFT_PART_SRC

      go mod tidy
      make build

      install -DT "./cmd/device-mqtt" "$SNAPCRAFT_PART_INSTALL/bin/device-mqtt"
      install -DT "./cmd/res/configuration.toml" "$SNAPCRAFT_PART_INSTALL/config/device-mqtt/res/configuration.toml"

      install -DT "./cmd/res/devices/mqtt.test.device.toml" \
        "$SNAPCRAFT_PART_INSTALL/config/device-mqtt/res/devices/mqtt.test.device.toml"
      install -DT "./cmd/res/devices/mqtt.test.device.toml" \
        "$SNAPCRAFT_PART_INSTALL/config/device-mqtt/res/devices/mqtt.test.device.toml"
      install -DT "./cmd/res/profiles/mqtt.test.device.profile.yml" \
        "$SNAPCRAFT_PART_INSTALL/config/device-mqtt/res/profiles/mqtt.test.device.profile.yml"

      install -DT "./Attribution.txt" \
         "$SNAPCRAFT_PART_INSTALL/usr/share/doc/device-mqtt/Attribution.txt"
      install -DT "./LICENSE" \
         "$SNAPCRAFT_PART_INSTALL/usr/share/doc/device-mqtt/LICENSE"

  config-common:
    plugin: dump
    source: snap/local/runtime-helpers

  metadata:
    plugin: nil
    source-type: git
    build-packages: [wget, ca-certificates]
    override-pull: |
      # download the metadata in AppStream format
      # this is temp URL pending PR https://github.com/canonical/edgex-snap-metadata/pull/4
      wget -d https://raw.githubusercontent.com/farshidtz/edgex-snap-metadata/appstream/edgex-device-mqtt.metainfo.xml

      # get the version from git tag
      cd $SNAPCRAFT_PROJECT_DIR
      if git describe ; then
        VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
      else
        VERSION="0.0.0"
      fi
      
      # write version to file for the build
      echo $VERSION > ./VERSION

      snapcraftctl set-version $VERSION

    parse-info: [edgex-device-mqtt.metainfo.xml]