name: edgex-device-mqtt
base: core20
license: Apache-2.0
summary: EdgeX MQTT Device Service
description: Refer to https://snapcraft.io/edgex-device-mqtt
adopt-info: device-mqtt

architectures:
  - build-on: amd64
  - build-on: arm64

grade: stable
confinement: strict

# 1: edinburgh, geneva, hanoi
# 2: ireland, jakarta
epoch: 2

slots:
  edgex-secretstore-token:
    interface: content
    source:
      write: [$SNAP_DATA/device-mqtt]

plugs:
  device-mqtt-config:
    interface: content
    target: $SNAP_DATA/config/device-mqtt

  # deprecated
  device-config:
    interface: content
    target: $SNAP_DATA/config/device-mqtt

apps:
  device-mqtt:
    adapter: full
    command: bin/device-mqtt --configDir $SNAP_DATA/config/device-mqtt --configProvider --registry -profile res
    command-chain:
      - bin/source-env-file.sh
    environment:
      DEVICE_PROFILESDIR: $SNAP_DATA/config/device-mqtt/res/profiles
      DEVICE_DEVICESDIR: $SNAP_DATA/config/device-mqtt/res/devices
      SECRETSTORE_TOKENFILE: $SNAP_DATA/device-mqtt/secrets-token.json
    daemon: simple
    install-mode: disable
    plugs: [network, network-bind]

parts:
  helper-go:
    source: snap/local/helper-go
    plugin: make
    build-snaps:
      - go/1.20/stable
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      make build
      install -DT ./helper-go $SNAPCRAFT_PART_INSTALL/bin/helper-go

  device-mqtt:
    source: .
    plugin: make
    build-packages: 
      - git
    build-snaps:
      - go/1.20/stable
    override-build: |
      cd $SNAPCRAFT_PART_SRC

      if git describe ; then
        VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
      else
        VERSION="0.0.0"
      fi

      # set the version of this snap
      snapcraftctl set-version $VERSION

      # write version to file for the build
      echo $VERSION > ./VERSION

      make build
      install -DT "./cmd/device-mqtt" "$SNAPCRAFT_PART_INSTALL/bin/device-mqtt"
      
      RES=$SNAPCRAFT_PART_INSTALL/config/device-mqtt/res/
      mkdir -p $RES
      cp    cmd/res/configuration.toml $RES
      cp -r cmd/res/devices $RES
      cp -r cmd/res/profiles $RES

      DOC=$SNAPCRAFT_PART_INSTALL/usr/share/doc/device-mqtt
      mkdir -p $DOC
      cp Attribution.txt $DOC/Attribution.txt
      cp LICENSE $DOC/LICENSE


  local-bin:
    plugin: dump
    source: snap/local/bin
    organize:
      source-env-file.sh: bin/source-env-file.sh

